# use with: logging.config.dictConfig(yaml.load(open('logging.yml', 'r')))
 
# Formatters detailed here: http://docs.python.org/2/library/logging.html#logrecord-attributes
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detail:
    format: '%(asctime)s - %(levelname)s - File: %(filename)s - %(funcName)s() - Line: %(lineno)d -  %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  D:
    class: logging_ext.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    when: W0
    backupCount: 4
    filename: logs/log.log
    encoding: utf-8
  E:
    class: logging_ext.TimedRotatingFileHandler
    level: ERROR
    formatter: detail
    when: W0
    backupCount: 4
    filename: logs/error.log
    encoding: utf-8

root:
  level: DEBUG
  handlers: [console, D, E]
  propagate: true